kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: wallets
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: wallets
subjects:
- kind: User
  name: system:serviceaccount:default:default
roleRef:
  kind: Role
  name: wallets
  apiGroup: rbac.authorization.k8s.io